services:
  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    networks:
      - spring-network
    volumes:
      # Mapear o arquivo JSON local para dentro do container
      - ./src/main/resources/tasks.json:/app/resources/tasks.json
networks:
  spring-network:
    driver: bridge
